<?php

return [

    'users' => [
        [
            'name' => 'Alessandro',
            'surname' => 'Ferrari',
            'email' => 'alessandroferrari@example.com',
            'password' => 'password123',
        ],
        [
            'name' => 'Giulia',
            'surname' => 'Russo',
            'email' => 'giuliarusso@example.com',
            'password' => 'password456',
        ],
        [
            'name' => 'Federico',
            'surname' => 'Bianchi',
            'email' => 'federicobianchi@example.com',
            'password' => 'password789',
        ],
        [
            'name' => 'Elisa',
            'surname' => 'Romano',
            'email' => 'elisaromano@example.com',
            'password' => 'password1011',
        ],
        [
            'name' => 'Matteo',
            'surname' => 'Gallo',
            'email' => 'matteogallo@example.com',
            'password' => 'password1213',
        ],
        [
            'name' => 'Francesca',
            'surname' => 'Costa',
            'email' => 'francescacosta@example.com',
            'password' => 'password1415',
        ],
        [
            'name' => 'Lorenzo',
            'surname' => 'Fontana',
            'email' => 'lorenzofontana@example.com',
            'password' => 'password1617',
        ],
        [
            'name' => 'Sara',
            'surname' => 'Marini',
            'email' => 'saramarini@example.com',
            'password' => 'password1819',
        ],
        [
            'name' => 'Davide',
            'surname' => 'Moretti',
            'email' => 'davidemoretti@example.com',
            'password' => 'password2021',
        ],
        [
            'name' => 'Chiara',
            'surname' => 'Santoro',
            'email' => 'chiarasantoro@example.com',
            'password' => 'password2223',
        ],
        [
            'name' => 'Giorgio',
            'surname' => 'Bruno',
            'email' => 'giorgiobruno@example.com',
            'password' => 'password2425',
        ],
        [
            'name' => 'Martina',
            'surname' => 'Pellegrini',
            'email' => 'martinapellegrini@example.com',
            'password' => 'password2627',
        ],
        [
            'name' => 'Riccardo',
            'surname' => 'Lombardi',
            'email' => 'riccardolombardi@example.com',
            'password' => 'password2829',
        ],
        [
            'name' => 'Valentina',
            'surname' => 'Rizzo',
            'email' => 'valentinarizzo@example.com',
            'password' => 'password3031',
        ],
        [
            'name' => 'Stefano',
            'surname' => 'Conti',
            'email' => 'stefanoconti@example.com',
            'password' => 'password3233',
        ],
    ],

    'restaurants' => [
        [
            'name' => 'Ristorante La Scala',
            'image' => 'https://images.lacucinaitaliana.it/gallery/123259/Big/bb3ff4b8-0af6-47ca-8d88-6ac1c2134f2b.jpg',
            'address' => 'Via Verdi 1, Milano',
            'phone' => '+39 3214567890',
            'vat' => 'IT10293847561',
            'user_id' => 1
        ],
        [
            'name' => 'Trattoria Il Duomo',
            'image' => 'https://www.flawlessmilano.com/wp-content/uploads/2017/01/Ristorante-Arlati.jpg?x53037',
            'address' => 'Piazza Duomo 2, Milano',
            'phone' => '+39 3216549870',
            'vat' => 'IT11223344556',
            'user_id' => 2
        ],
        [
            'name' => 'Pizzeria Bella Milano',
            'image' => 'https://trattoria.bertame.it/wp-content/uploads/sites/4/2019/09/color-007-1.jpg',
            'address' => 'Via Dante 3, Milano',
            'phone' => '+39 3217896541',
            'vat' => 'IT12345678901',
            'user_id' => 3
        ],
        [
            'name' => 'Osteria Alla Scala',
            'image' => 'https://media-assets.lacucinaitaliana.it/photos/61fabe8151116b1ead93066e/16:9/w_2560%2Cc_limit/Landscape-osterie.jpg',
            'address' => 'Via Manzoni 4, Milano',
            'phone' => '+39 3214561234',
            'vat' => 'IT23456789012',
            'user_id' => 4
        ],
        [
            'name' => 'Ristorante La Rinascente',
            'image' => 'https://d1tm14lrsghf7q.cloudfront.net/media/files/rtf/2019_06_FRAME/La_Rinascente_Milan-10.jpg',
            'address' => 'Via Vittorio Emanuele 5, Milano',
            'phone' => '+39 3216543210',
            'vat' => 'IT34567890123',
            'user_id' => 5
        ],
        [
            'name' => 'Trattoria Il Naviglio',
            'image' => 'https://i.pinimg.com/originals/c2/bb/c1/c2bbc13ebc4c84d9e969eedfa4f8493a.jpg',
            'address' => 'Via Alzaia 6, Milano',
            'phone' => '+39 3217891234',
            'vat' => 'IT45678901234',
            'user_id' => 6
        ],
        [
            'name' => 'Pizzeria Milano Centrale',
            'image' => 'https://assets-global.website-files.com/59baab33dea09c0001ac218f/59c7b5eba99f5700012f416b_obica-mozzarella-bar-milano-centrale-01.jpg',
            'address' => 'Piazza Duca d\'Aosta 7, Milano',
            'phone' => '+39 3214569870',
            'vat' => 'IT56789012345',
            'user_id' => 7
        ],
        [
            'name' => 'Osteria Brera',
            'image' => 'https://www.venetianlasvegas.com/content/dam/venetian/restaurants/brera-osteria/interior-3_1920x1080.jpg.resize.0.0.1200.630.jpg?ignorecache=true',
            'address' => 'Via Brera 8, Milano',
            'phone' => '+39 3216547890',
            'vat' => 'IT67890123456',
            'user_id' => 8
        ],
        [
            'name' => 'Osteria Sforzesca',
            'image' => 'https://www.veronawinesuites.com/data/files/clm/185/tour-osterie_1920_1920.jpg',
            'address' => 'Via Castello 9, Milano',
            'phone' => '+39 3217894561',
            'vat' => 'IT78901234567',
            'user_id' => 9
        ],
        [
            'name' => 'Trattoria Porta Romana',
            'image' => 'https://portaromana.com.br/wp-content/uploads/2019/04/trattoria-porta-romana-curitiba-02.jpg',
            'address' => 'Corso di Porta Romana 10, Milano',
            'phone' => '+39 3214563210',
            'vat' => 'IT89012345678',
            'user_id' => 10
        ],
        [
            'name' => 'Pizzeria Porta Ticinese',
            'image' => 'https://www.pizzeriatradizionale.com/wp-content/uploads/2017/06/interno-6-Pizzeria-Tradizionale-Ripa-di-Porta-Ticinese-7-%E2%80%93-20144-MIlano.jpg',
            'address' => 'Via Vigevano 11, Milano',
            'phone' => '+39 3216541234',
            'vat' => 'IT90123456789',
            'user_id' => 11
        ],
        [
            'name' => 'Ristorante San Babila',
            'image' => 'https://b.zmtcdn.com/data/pictures/3/16300053/4547a1ff1cf86f2baf8ac6a026f2ff39.jpg',
            'address' => 'Piazza San Babila 12, Milano',
            'phone' => '+39 3217896543',
            'vat' => 'IT01234567890',
            'user_id' => 12
        ],
        [
            'name' => 'Osteria Bovisa',
            'image' => 'https://www.theeatculture.com/wp-content/uploads/2018/11/osteria-milano_5.jpg',
            'address' => 'Via Bovisasca 13, Milano',
            'phone' => '+39 3214569876',
            'vat' => 'IT12345098765',
            'user_id' => 13
        ],
        [
            'name' => 'Trattoria Cadorna',
            'image' => 'https://cdn.sanity.io/images/v3ujbg13/production/6cdf2f72301e8ff147f9110547fee351ae978351-7140x4762.jpg?w=2400&auto=format',
            'address' => 'Piazza Cadorna 14, Milano',
            'phone' => '+39 3216547896',
            'vat' => 'IT23456087654',
            'user_id' => 14
        ],
        [
            'name' => 'Pizzeria Porta Venezia',
            'image' => 'https://www.scattidigusto.it/wp-content/uploads/2019/11/Cocciuto-nuova-pizzeria-Milano-via-Melzo-Porta-Venezia-sedute.jpg',
            'address' => 'Corso Buenos Aires 15, Milano',
            'phone' => '+39 3217894567',
            'vat' => 'IT34567076543',
            'user_id' => 15
        ],
    ],


    'types' => [
        [
            'type' => 'Mexican',
        ],
        [
            'type' => 'Italian',
        ],
        [
            'type' => 'Pizzeria',
        ],
        [
            'type' => 'Chinese',
        ],
        [
            'type' => 'Japanese',
        ],
        [
            'type' => 'Thai',
        ],
        [
            'type' => 'Indian',
        ],
        [
            'type' => 'Fusion',
        ],
        [
            'type' => 'Greek',
        ],
        [
            'type' => 'Steakhouse'
        ],
        [
            'type' => 'French',
        ],
        [
            'type' => 'Seafood',
        ],
        [
            'type' => 'Vegetarian',
        ],
        [
            'type' => 'Vegan',
        ],
        [
            'type' => 'Middle Eastern',
        ],
    ],


    'dishes' => [
        [
            "name" => "Spaghetti Carbonara",
            "image" => "https://www.ricettaidea.it/articoli/ricette-regionali/lazio/original_spaghetti-alla-carbonara.jpg",
            "description" => "Spaghetti with egg cream and pancetta.",
            "ingredients" => ["Spaghetti", "Eggs", "Pancetta", "Pecorino", "Pepper"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Pizza Margherita",
            "image" => "https://vitaitaliantours.com.au/wp-content/uploads/2016/03/Neapolitan-Pizza-Margherita.jpg",
            "description" => "Classic pizza with tomato and mozzarella.",
            "ingredients" => ["Tomato", "Mozzarella", "Basil", "Olive Oil", "Salt"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Mushroom Risotto",
            "image" => "https://blog.giallozafferano.it/peperoncino88/wp-content/uploads/2017/10/DSC_0020.jpg",
            "description" => "Creamy risotto with porcini mushrooms.",
            "ingredients" => ["Rice", "Mushrooms", "Broth", "Butter", "Parmesan"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "Lasagna",
            "image" => "https://facts.net/wp-content/uploads/2023/05/Slice-of-lasagna.jpeg",
            "description" => "Layers of pasta with meat sauce and béchamel.",
            "ingredients" => ["Pasta", "Meat Sauce", "Béchamel", "Parmesan", "Mozzarella"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Caprese Salad",
            "image" => "https://www.tasteoftravel.at/wp-content/uploads/Rezept-Caprese-Salat.jpg",
            "description" => "Tomato and mozzarella with fresh basil.",
            "ingredients" => ["Tomato", "Mozzarella", "Basil", "Olive Oil", "Salt"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Chicken Cacciatore",
            "image" => "https://4.bp.blogspot.com/-sLQkRHQnI0g/V5y0Lj1C6QI/AAAAAAAAIL0/B1fHSzXrZaMAgZTOwgzFpNU0gAhVVT_RQCLcB/s640/pollo_padella.jpg",
            "description" => "Braised chicken with tomato and olives.",
            "ingredients" => ["Chicken", "Tomato", "Olives", "Wine", "Rosemary"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        [
            "name" => "Fettuccine Alfredo",
            "image" => "https://www.thechunkychef.com/wp-content/uploads/2016/02/Roasted-Garlic-Cream-Sauce-6-1.jpg",
            "description" => "Pasta with creamy butter and parmesan sauce.",
            "ingredients" => ["Fettuccine", "Butter", "Parmesan", "Cream", "Pepper"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Tomato Bruschetta",
            "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/11/ricetta-bruschetta-pomodoro/_jcr_content/header-par/image_single.img.jpg/1596625322419.jpg",
            "description" => "Toasted bread with fresh tomato and basil.",
            "ingredients" => ["Bread", "Tomato", "Basil", "Garlic", "Olive Oil"],
            "price" => 5.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Tiramisu",
            "image" => "https://www.divella.it/wp-content/uploads/2022/12/tiramisu.jpg",
            "description" => "Coffee-flavored dessert with mascarpone and ladyfingers.",
            "ingredients" => ["Mascarpone", "Ladyfingers", "Coffee", "Cocoa", "Sugar"],
            "price" => 6.00,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Gnocchi with Pesto",
            "image" => "https://lognocco.it/wp-content/uploads/2018/07/9-preparazione-ricetta-gnocchi-pesto.jpg",
            "description" => "Potato gnocchi with fresh pesto.",
            "ingredients" => ["Gnocchi", "Basil", "Garlic", "Pine Nuts", "Parmesan"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 12,
        ],
        [
            "name" => "Beef Tagliata",
            "image" => "https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/01/Tagliata-di-manzo.jpg",
            "description" => "Grilled beef with arugula and parmesan.",
            "ingredients" => ["Beef", "Arugula", "Parmesan", "Olive Oil", "Salt"],
            "price" => 18.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Penne Arrabbiata",
            "image" => "https://cdn.ilclubdellericette.it/wp-content/uploads/2021/09/penne-arrabbiata-1280x720.jpg",
            "description" => "Spicy pasta with tomato and chili pepper.",
            "ingredients" => ["Penne", "Tomato", "Chili Pepper", "Garlic", "Olive Oil"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        [
            "name" => "Rice Balls",
            "image" => "https://www.thespruceeats.com/thmb/WlPKK4-UvBDf9V2f0h014AUJ1W8=/1500x998/filters:fill(auto,1)/rice-balls-2031330-26-5b3fd34346e0fb00376633fa.jpg",
            "description" => "Fried rice balls filled with meat sauce.",
            "ingredients" => ["Rice", "Meat Sauce", "Peas", "Cheese", "Breadcrumbs"],
            "price" => 7.50,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Fried Calamari",
            "image" => "https://www.willcookforsmiles.com/wp-content/uploads/2021/07/Calamari-6-1024x1536.jpg",
            "description" => "Fried calamari served with lemon.",
            "ingredients" => ["Calamari", "Flour", "Oil", "Lemon", "Salt"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Pasta and Beans",
            "image" => "https://slowcookermeals.com/wp-content/uploads/2022/08/Crock-Pot-Pasta-Fagioli-1.jpg",
            "description" => "Pasta soup with beans and pancetta.",
            "ingredients" => ["Pasta", "Beans", "Pancetta", "Tomato", "Rosemary"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        // Additional dishes
        [
            "name" => "Seafood Linguine",
            "image" => "https://www.tasteofhome.com/wp-content/uploads/2017/10/Mediterranean-Shrimp-Linguine_exps120872_SD2232457C08_26_3bC_RMS.jpg",
            "description" => "Linguine with mixed seafood.",
            "ingredients" => ["Linguine", "Shrimp", "Clams", "Tomato", "Garlic"],
            "price" => 16.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Vegetarian Pizza",
            "image" => "https://lacucharaveggie.com/wp-content/uploads/2016/03/v-img-043.jpg",
            "description" => "Pizza with mixed vegetables.",
            "ingredients" => ["Dough", "Tomato", "Mozzarella", "Bell Peppers", "Olives"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Chicken Parmesan",
            "image" => "https://www.onceuponachef.com/images/2019/04/Chicken-Parmesan-15-1200x1553.jpg",
            "description" => "Breaded chicken with parmesan.",
            "ingredients" => ["Chicken", "Breadcrumbs", "Parmesan", "Tomato Sauce", "Mozzarella"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Grilled Salmon",
            "image" => "https://www.cookingclassy.com/wp-content/uploads/2018/05/grilled-lemon-herb-salmon-7.jpg",
            "description" => "Salmon grilled with herbs.",
            "ingredients" => ["Salmon", "Olive Oil", "Lemon", "Garlic", "Dill"],
            "price" => 18.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Chocolate Cake",
            "image" => "https://sallysbakingaddiction.com/wp-content/uploads/2013/04/triple-chocolate-cake-4.jpg",
            "description" => "Rich chocolate layered cake.",
            "ingredients" => ["Chocolate", "Flour", "Sugar", "Eggs", "Butter"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Minestrone Soup",
            "image" => "https://slowcookermeals.com/wp-content/uploads/2022/08/Crock-Pot-Pasta-Fagioli-4-1024x1024.jpg",
            "description" => "Hearty vegetable soup.",
            "ingredients" => ["Tomato", "Carrot", "Celery", "Beans", "Pasta"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Eggplant Parmesan",
            "image" => "https://www.andiemitchell.com/wp-content/uploads/2019/03/healthy_baked_eggplant_parmesan-1.jpg",
            "description" => "Breaded eggplant with cheese.",
            "ingredients" => ["Eggplant", "Breadcrumbs", "Parmesan", "Tomato Sauce", "Mozzarella"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Garlic Bread",
            "image" => "https://www.cookingclassy.com/wp-content/uploads/2019/09/garlic-bread-04.jpg",
            "description" => "Toasted bread with garlic butter.",
            "ingredients" => ["Bread", "Butter", "Garlic", "Parsley", "Salt"],
            "price" => 4.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Lamb Chops",
            "image" => "https://thescranline.com/wp-content/uploads/2024/01/GREEK-LAMB-CHOPS-WEB-05.jpg",
            "description" => "Grilled lamb with rosemary.",
            "ingredients" => ["Lamb", "Rosemary", "Garlic", "Olive Oil", "Salt"],
            "price" => 20.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Cheeseburger",
            "image" => "https://i.pinimg.com/originals/66/87/aa/6687aabb09412dfb3609b30dc327c206.png",
            "description" => "Burger with cheese and toppings.",
            "ingredients" => ["Beef", "Cheese", "Lettuce", "Tomato", "Bun"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        [
            "name" => "Pasta Primavera",
            "image" => "https://www.cookingclassy.com/wp-content/uploads/2018/09/pasta-primavera-1.jpg",
            "description" => "Pasta with fresh vegetables.",
            "ingredients" => ["Pasta", "Bell Peppers", "Zucchini", "Tomato", "Garlic"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Scampi",
            "image" => "https://mymorningmocha.com/wp-content/uploads/2023/03/Drizzling-garlic-butter-over-prawns-683x1024.jpg",
            "description" => "Shrimp in garlic butter sauce.",
            "ingredients" => ["Shrimp", "Garlic", "Butter", "Lemon", "Parsley"],
            "price" => 17.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Caesar Salad",
            "image" => "https://www.jessicagavin.com/wp-content/uploads/2019/07/caesar-salad-10.jpg",
            "description" => "Salad with Caesar dressing.",
            "ingredients" => ["Lettuce", "Croutons", "Parmesan", "Caesar Dressing", "Chicken"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Clam Chowder",
            "image" => "https://therecipecritic.com/wp-content/uploads/2018/10/Clam-Chowder-5.jpg",
            "description" => "Creamy soup with clams.",
            "ingredients" => ["Clams", "Potato", "Cream", "Onion", "Bacon"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "BBQ Ribs",
            "image" => "https://www.barossafinefoods.com.au/glide-cache/containers/main/2020_bff_porkribs_bbq_website-2.jpg/03d880f2ca84b83fdeb147548e7d9b12.jpg",
            "description" => "Ribs with BBQ sauce.",
            "ingredients" => ["Ribs", "BBQ Sauce", "Garlic", "Brown Sugar", "Paprika"],
            "price" => 18.50,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Veggie Burger",
            "image" => "https://cupfulofkale.com/wp-content/uploads/2017/08/Vegan-Spicy-Bean-Burgers-720x720.jpg.webp",
            "description" => "Vegetarian burger with toppings.",
            "ingredients" => ["Veggie Patty", "Lettuce", "Tomato", "Cheese", "Bun"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Stuffed Peppers",
            "image" => "https://www.eatwell101.com/wp-content/uploads/2018/05/low-carb-stuffed-bell-peppers-3.jpg",
            "description" => "Peppers stuffed with rice and meat.",
            "ingredients" => ["Bell Peppers", "Rice", "Ground Beef", "Tomato Sauce", "Cheese"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Fish Tacos",
            "image" => "https://www.eatwell101.com/wp-content/uploads/2022/06/fish-tacos-recipe-cod.jpg",
            "description" => "Tacos with fried fish.",
            "ingredients" => ["Fish", "Tortilla", "Cabbage", "Lime", "Sour Cream"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "French Onion Soup",
            "image" => "https://valentinascorner.com/wp-content/uploads/2020/01/Fish-Taco-Recipe-1-1.jpg",
            "description" => "Soup with caramelized onions.",
            "ingredients" => ["Onions", "Beef Broth", "Bread", "Cheese", "Thyme"],
            "price" => 7.50,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "Pulled Pork Sandwich",
            "image" => "https://www.almanac.com/sites/default/files/styles/max_2600x2600/public/recipe-pulled_pork.jpg?itok=wCRki62R",
            "description" => "Sandwich with pulled pork.",
            "ingredients" => ["Pulled Pork", "BBQ Sauce", "Bun", "Pickles", "Onion"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 6,
        ],

        [
            "name" => "Grilled Chicken",
            "image" => "https://www.averiecooks.com/wp-content/uploads/2019/06/limecilantrochicken-650x1000.jpg",
            "description" => "Chicken grilled with herbs.",
            "ingredients" => ["Chicken", "Olive Oil", "Lemon", "Garlic", "Rosemary"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "Spaghetti Bolognese",
            "image" => "https://static.fanpage.it/wp-content/uploads/sites/22/2021/06/spaghetti-bolognese.jpg",
            "description" => "Spaghetti with meat sauce.",
            "ingredients" => ["Spaghetti", "Ground Beef", "Tomato", "Onion", "Garlic"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 14,
        ],
        [
            "name" => "Chicken Alfredo",
            "image" => "https://iwashyoudry.com/wp-content/uploads/2022/08/Chicken-Alfredo-Low-Res-21.jpg",
            "description" => "Pasta with creamy Alfredo sauce.",
            "ingredients" => ["Pasta", "Chicken", "Cream", "Parmesan", "Garlic"],
            "price" => 13.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Beef Stroganoff",
            "image" => "https://ohsweetbasil.com/wp-content/uploads/easy-ground-beef-stroganoff-recipe-8.jpg",
            "description" => "Beef with creamy mushroom sauce.",
            "ingredients" => ["Beef", "Mushrooms", "Sour Cream", "Onion", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Vegetable Stir Fry",
            "image" => "https://fedandfit.com/wp-content/uploads/2021/11/211112_Vegetable-Stir-Fry-05.jpg",
            "description" => "Stir-fried mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Broccoli", "Carrots", "Soy Sauce", "Garlic"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Roast Beef",
            "image" => "https://static01.nyt.com/images/2015/12/09/dining/09COOKING-BEEFROAST3/09COOKING-BEEFROAST3-superJumbo.jpg",
            "description" => "Slow-cooked roast beef.",
            "ingredients" => ["Beef", "Garlic", "Rosemary", "Olive Oil", "Salt"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Shrimp Alfredo",
            "image" => "https://www.dinneratthezoo.com/wp-content/uploads/2018/06/shrimp-alfredo-5.jpg",
            "description" => "Pasta with shrimp in Alfredo sauce.",
            "ingredients" => ["Pasta", "Shrimp", "Cream", "Parmesan", "Garlic"],
            "price" => 16.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Chicken Caesar Salad",
            "image" => "https://www.deliciousmeetshealthy.com/wp-content/uploads/2021/06/Chicken-Caesar-Salad-4-768x1156.jpg",
            "description" => "Salad with chicken and Caesar dressing.",
            "ingredients" => ["Lettuce", "Chicken", "Croutons", "Parmesan", "Caesar Dressing"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Garlic Shrimp",
            "image" => "https://bigoven-res.cloudinary.com/image/upload/t_recipe-1280/garlic-shrimp-10782d.jpg",
            "description" => "Shrimp in garlic butter.",
            "ingredients" => ["Shrimp", "Garlic", "Butter", "Lemon", "Parsley"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Beef Tacos",
            "image" => "https://i.pinimg.com/originals/e7/e2/34/e7e2342f999776e4fe028e18672ac21d.jpg",
            "description" => "Tacos with beef and toppings.",
            "ingredients" => ["Beef", "Tortilla", "Lettuce", "Tomato", "Cheese"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Chicken Tacos",
            "image" => "https://s23209.pcdn.co/wp-content/uploads/2019/08/Easy-Chicken-TacosIMG_9890.jpg",
            "description" => "Tacos with chicken and toppings.",
            "ingredients" => ["Chicken", "Tortilla", "Lettuce", "Tomato", "Cheese"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Fish Tacos",
            "image" => "https://www.platingpixels.com/wp-content/uploads/2021/01/Beer-Battered-Fish-Tacos-recipe-9.jpg",
            "description" => "Tacos with fish and toppings.",
            "ingredients" => ["Fish", "Tortilla", "Cabbage", "Lime", "Sour Cream"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Vegetarian Tacos",
            "image" => "https://www.twospoons.ca/wp-content/uploads/2020/07/best-vegan-taco-recipe-easy-how-to-make-vegan-tacos-twospoons-5-1365x2048.jpg",
            "description" => "Tacos with mixed vegetables.",
            "ingredients" => ["Tortilla", "Bell Peppers", "Onion", "Corn", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "BBQ Chicken Pizza",
            "image" => "https://carlsbadcravings.com/wp-content/uploads/2020/06/BBQ-Chicken-Pizza-v17a.jpg",
            "description" => "Pizza with BBQ chicken.",
            "ingredients" => ["Dough", "BBQ Sauce", "Chicken", "Onion", "Mozzarella"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Pepperoni Pizza",
            "image" => "http://fillyourplate.org/blog/wp-content/uploads/2015/02/bigstock-Hot-Homemade-Pepperoni-Pizza-74542819.jpg",
            "description" => "Pizza with pepperoni.",
            "ingredients" => ["Dough", "Tomato Sauce", "Pepperoni", "Mozzarella", "Olive Oil"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Four Cheese Pizza",
            "image" => "https://www.tasteatlas.com/images/recipes/7e6c5e28f707410e9e25608b92b376b1.jpg?mw=910",
            "description" => "Pizza with four types of cheese.",
            "ingredients" => ["Dough", "Tomato Sauce", "Mozzarella", "Parmesan", "Gorgonzola", "Ricotta"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Hawaiian Pizza",
            "image" => "https://northshoretaverntownsville.com.au/wp-content/uploads/2023/10/11.jpg",
            "description" => "Pizza with ham and pineapple.",
            "ingredients" => ["Dough", "Tomato Sauce", "Ham", "Pineapple", "Mozzarella"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Buffalo Wings",
            "image" => "http://delightsofculinaria.com/wp-content/uploads/2013/02/dsc_1110.jpg",
            "description" => "Spicy chicken wings.",
            "ingredients" => ["Chicken Wings", "Buffalo Sauce", "Butter", "Garlic", "Celery"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Mozzarella Sticks",
            "image" => "https://vignette1.wikia.nocookie.net/laurainthekitchen/images/8/89/IMG_3457.jpg/revision/latest?cb=20140605071844",
            "description" => "Fried mozzarella sticks.",
            "ingredients" => ["Mozzarella", "Breadcrumbs", "Eggs", "Flour", "Marinara Sauce"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Nuggets",
            "image" => "https://thetoastedpinenut.com/wp-content/uploads/2017/08/IMG_5288.jpg",
            "description" => "Breaded and fried chicken pieces.",
            "ingredients" => ["Chicken", "Breadcrumbs", "Eggs", "Flour", "Ketchup"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Pork Chops",
            "image" => "https://www.porkcdn.com/recipes/HR/Grilled_Pork_Chops_with_Basil-Garlic_Rub_HR.jpg",
            "description" => "Grilled pork chops with herbs.",
            "ingredients" => ["Pork Chops", "Olive Oil", "Garlic", "Rosemary", "Salt"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Lamb Curry",
            "image" => "https://www.thespruceeats.com/thmb/6dNkdIvw7UrZ_GeNp5oBhI9q8CE=/6051x3404/smart/filters:no_upscale()/indian-lamb-curry-1957560-Hero-5b699ec1c9e77c005006d572.jpg",
            "description" => "Spicy lamb curry with rice.",
            "ingredients" => ["Lamb", "Curry Powder", "Coconut Milk", "Onion", "Garlic"],
            "price" => 18.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Chicken Curry",
            "image" => "https://dinnerthendessert.com/wp-content/uploads/2018/04/Indian-Chicken-Korma1-640x640.jpg",
            "description" => "Spicy chicken curry with rice.",
            "ingredients" => ["Chicken", "Curry Powder", "Coconut Milk", "Onion", "Garlic"],
            "price" => 16.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Beef Curry",
            "image" => "https://www.simplejoy.com/wp-content/uploads/2020/06/beef-curry-recipe-2-1365x2048.jpg",
            "description" => "Spicy beef curry with rice.",
            "ingredients" => ["Beef", "Curry Powder", "Coconut Milk", "Onion", "Garlic"],
            "price" => 17.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Vegetable Curry",
            "image" => "https://i.pinimg.com/736x/dc/03/7a/dc037a83805ec7639e51e8462adec7b6.jpg",
            "description" => "Spicy vegetable curry with rice.",
            "ingredients" => ["Bell Peppers", "Carrots", "Coconut Milk", "Onion", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Salmon Sashimi",
            "image" => "https://aubreyskitchen.com/wp-content/uploads/2021/01/salmon-sashimi-recipe-768x768.jpg",
            "description" => "Fresh salmon sashimi.",
            "ingredients" => ["Salmon", "Soy Sauce", "Wasabi", "Ginger", "Lemon"],
            "price" => 20.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],

        [
            "name" => "Tuna Sashimi",
            "image" => "https://oshisushis.com/wp-content/uploads/2020/06/Tuna-Sashimi-812x812.png",
            "description" => "Fresh tuna sashimi.",
            "ingredients" => ["Tuna", "Soy Sauce", "Wasabi", "Ginger", "Lemon"],
            "price" => 20.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Beef Stir Fry",
            "image" => "https://thegirlonbloor.com/wp-content/uploads/2019/04/The-best-Beef-stir-fry-3-790x1185.jpg",
            "description" => "Stir-fried beef with vegetables.",
            "ingredients" => ["Beef", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Chicken Stir Fry",
            "image" => "https://tatyanaseverydayfood.com/wp-content/uploads/2019/03/Chicken-Teriyaki-Stir-Fry.jpg",
            "description" => "Stir-fried chicken with vegetables.",
            "ingredients" => ["Chicken", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Pork Stir Fry",
            "image" => "https://s3-us-east-2.amazonaws.com/thesaltymarshmallow/wp-content/uploads/2018/01/03061735/pork-stir-fry2.jpg",
            "description" => "Stir-fried pork with vegetables.",
            "ingredients" => ["Pork", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Vegetable Stir Fry",
            "image" => "https://natashaskitchen.com/wp-content/uploads/2020/08/Vegetable-Stir-Fry-2.jpg",
            "description" => "Stir-fried mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Broccoli", "Carrots", "Soy Sauce", "Garlic"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Fish and Chips",
            "image" => "https://nicelandseafood.com/wp-content/uploads/2020/04/classic-fish-and-chips-with-haddock.jpg",
            "description" => "Fried fish with chips.",
            "ingredients" => ["Fish", "Potatoes", "Flour", "Oil", "Salt"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Chicken and Chips",
            "image" => "https://timi-codes.github.io/BetaChop/UI/img/chickenndchips.jpg",
            "description" => "Fried chicken with chips.",
            "ingredients" => ["Chicken", "Potatoes", "Flour", "Oil", "Salt"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Prawn Cocktail",
            "image" => "https://www.deliciousmagazine.co.uk/wp-content/uploads/2019/09/prawn-cocktail.jpg",
            "description" => "Prawns in a creamy sauce.",
            "ingredients" => ["Prawns", "Mayonnaise", "Ketchup", "Lemon", "Lettuce"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],








        [
            "name" => "Stuffed Mushrooms",
            "image" => "https://i.pinimg.com/originals/49/86/3c/49863c5b1ee5348e5cdcdf3dafd5d033.jpg",
            "description" => "Mushrooms stuffed with cheese.",
            "ingredients" => ["Mushrooms", "Cheese", "Breadcrumbs", "Garlic", "Parsley"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Egg Salad",
            "image" => "https://theforkedspoon.com/wp-content/uploads/2019/07/Egg-Salad-9-700x1050.jpg",
            "description" => "Salad with boiled eggs.",
            "ingredients" => ["Eggs", "Lettuce", "Tomato", "Mayonnaise", "Onion"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Tuna Salad",
            "image" => "https://www.eatingbirdfood.com/wp-content/uploads/2021/01/tuna-salad-bowl-crackers-670x1005.jpg",
            "description" => "Salad with tuna.",
            "ingredients" => ["Tuna", "Lettuce", "Tomato", "Onion", "Olive Oil"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Salmon Salad",
            "image" => "https://www.acedarspoon.com/wp-content/uploads/2021/04/Mediterranean-Salmon-Bowl-Image-4-735x694.jpg",
            "description" => "Salad with salmon.",
            "ingredients" => ["Salmon", "Lettuce", "Tomato", "Onion", "Olive Oil"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Chicken Salad",
            "image" => "https://www.aspicyperspective.com/wp-content/uploads/2020/03/ultimate-southern-chicken-salad-recipe-12-650x875.jpg",
            "description" => "Salad with chicken.",
            "ingredients" => ["Chicken", "Lettuce", "Tomato", "Onion", "Olive Oil"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "Grilled Cheese Sandwich",
            "image" => "https://static01.nyt.com/images/2021/08/30/dining/as-grilled-cheese-sandwich-on-the-grill/as-grilled-cheese-sandwich-on-the-grill-threeByTwoMediumAt2X.jpg",
            "description" => "Sandwich with melted cheese.",
            "ingredients" => ["Bread", "Cheese", "Butter", "Garlic", "Parsley"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 14,
        ],
        [
            "name" => "Ham and Cheese Sandwich",
            "image" => "https://www.pumpkinnspice.com/wp-content/uploads/2016/08/grilled-ham-cheese-sandwich-26.jpg",
            "description" => "Sandwich with ham and cheese.",
            "ingredients" => ["Bread", "Ham", "Cheese", "Butter", "Garlic"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "Turkey Sandwich",
            "image" => "https://fthmb.tqn.com/z4fsO6WbzaVVXojI77-u2pWox_Q=/3867x2578/filters:fill(auto,1)/Baked-Turkey-Sandwich-58add8dd3df78c345bdf210c.jpg",
            "description" => "Sandwich with turkey.",
            "ingredients" => ["Bread", "Turkey", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 14,
        ],






        [
            "name" => "BLT Sandwich",
            "image" => "https://vikalinka.com/wp-content/uploads/2021/06/Maple-BLT-Sandwich-12-Edit.jpg",
            "description" => "Sandwich with bacon, lettuce, and tomato.",
            "ingredients" => ["Bread", "Bacon", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 14,
        ],
        [
            "name" => "Veggie Sandwich",
            "image" => "https://i.pinimg.com/originals/a5/f2/10/a5f21054fcc0f406d154a1d151fa1f04.jpg",
            "description" => "Sandwich with vegetables.",
            "ingredients" => ["Bread", "Lettuce", "Tomato", "Cucumber", "Avocado"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Pastrami Sandwich",
            "image" => "https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/kegziasw/8d328464-170c-4a4e-93d3-4e6757f2df0d.jpg",
            "description" => "Sandwich with pastrami.",
            "ingredients" => ["Bread", "Pastrami", "Mustard", "Pickles", "Cheese"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Reuben Sandwich",
            "image" => "https://www.simplyrecipes.com/thmb/d735twlFKqG5IgMClyozXhkpAGM=/4907x2760/smart/filters:no_upscale()/Simply-Recipes-Reuben-Sandwich-Lead-1b-df911d5d7fff4cbf986beeacb80b99c9.jpg",
            "description" => "Sandwich with corned beef and sauerkraut.",
            "ingredients" => ["Bread", "Corned Beef", "Sauerkraut", "Swiss Cheese", "Thousand Island Dressing"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Pulled Pork Sandwich",
            "image" => "https://www.cookingwithvinyl.com/wp-content/uploads/2015/01/Pulled-Pork.jpg",
            "description" => "Sandwich with pulled pork.",
            "ingredients" => ["Bread", "Pulled Pork", "BBQ Sauce", "Coleslaw", "Pickles"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Meatball Sandwich",
            "image" => "https://dailyappetite.com/wp-content/uploads/2019/02/Crockpot-Meatball-Subs-3.jpg",
            "description" => "Sandwich with meatballs.",
            "ingredients" => ["Bread", "Meatballs", "Marinara Sauce", "Provolone Cheese", "Parmesan"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Chicken Parmesan Sandwich",
            "image" => "https://www.thespruceeats.com/thmb/J22wsiGBc6vx32BKTZWGKV7R4zE=/3000x2001/filters:fill(auto,1)/ChickenParmesanSandwichHERO-950abfea32f542a493a0bb9f70912406.jpg",
            "description" => "Sandwich with chicken parmesan.",
            "ingredients" => ["Bread", "Chicken Parmesan", "Marinara Sauce", "Mozzarella", "Parmesan"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        [
            "name" => "Philly Cheesesteak",
            "image" => "https://thestayathomechef.com/wp-content/uploads/2020/09/Authentic-Philly-Cheesesteak-5.jpg",
            "description" => "Sandwich with steak and cheese.",
            "ingredients" => ["Bread", "Steak", "Cheese", "Onions", "Peppers"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Cubano Sandwich",
            "image" => "https://dinnerthendessert.com/wp-content/uploads/2021/01/Cuban-Sandwich-1x1-1.jpg",
            "description" => "Sandwich with ham, pork, and pickles.",
            "ingredients" => ["Bread", "Ham", "Pork", "Pickles", "Mustard"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Egg Salad Sandwich",
            "image" => "https://scm-assets.constant.co/scm/unilever/e9dc924f238fa6cc29465942875fe8f0/e24aeb52-ea33-4008-b898-dd81778119ac.jpg",
            "description" => "Sandwich with egg salad.",
            "ingredients" => ["Bread", "Egg Salad", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Shrimp Po' Boy",
            "image" => "https://www.simplyrecipes.com/thmb/NWR2yj5F6btUCzcJ9M3r4WsZk0M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Shrimp-Po-Boy-LEAD-22-33ab39c8d49249d688918b1039f72468.jpg",
            "description" => "Sandwich with fried shrimp.",
            "ingredients" => ["Bread", "Fried Shrimp", "Lettuce", "Tomato", "Remoulade Sauce"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 9,
        ],
        [
            "name" => "Turkey Club Sandwich",
            "image" => "https://www.thespruceeats.com/thmb/Mb1XDRC56r_qTsGuZllzWkgUJHk=/3600x0/filters:no_upscale():max_bytes(150000):strip_icc()/turkey-club-sandwich-recipe-996062-step-04-5c252ecec9e77c0001d6b56a.jpg",
            "description" => "Triple-decker sandwich with turkey, bacon, and lettuce.",
            "ingredients" => ["Bread", "Turkey", "Bacon", "Lettuce", "Tomato"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Italian Sub",
            "image" => "https://boarshead.scdn5.secure.raxcdn.com/img/_content/recipe/1501460417-that-s-italian-sub/detail-001.1490628991.jpg",
            "description" => "Sub with Italian meats and cheeses.",
            "ingredients" => ["Bread", "Salami", "Ham", "Provolone", "Olive Oil"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "BBQ Pulled Chicken Sandwich",
            "image" => "https://www.jessicagavin.com/wp-content/uploads/2015/06/barbecue-pulled-chicken-sandwiches.jpg",
            "description" => "Sandwich with BBQ pulled chicken.",
            "ingredients" => ["Bread", "Pulled Chicken", "BBQ Sauce", "Coleslaw", "Pickles"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        [
            "name" => "French Dip Sandwich",
            "image" => "https://www.cookingclassy.com/wp-content/uploads/2017/10/slow-cooker-french-dip-sandwiches-3.jpg",
            "description" => "Sandwich with roast beef and au jus.",
            "ingredients" => ["Bread", "Roast Beef", "Swiss Cheese", "Au Jus", "Onions"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 14,
        ],
        [
            "name" => "Buffalo Chicken Sandwich",
            "image" => "https://www.thespruceeats.com/thmb/A64fbBqBWccnWy2MpFmyu-yxbqY=/1893x0/filters:no_upscale():max_bytes(150000):strip_icc()/buffalo-chicken-sandwich-2937545-step-08-2dcdcca090694b558c394343ad8ed5a2.jpg",
            "description" => "Sandwich with buffalo chicken.",
            "ingredients" => ["Bread", "Buffalo Chicken", "Lettuce", "Tomato", "Blue Cheese Dressing"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "BBQ Brisket Sandwich",
            "image" => "https://cdn.mos.cms.futurecdn.net/tqztcMcTtPFSRSG2uSwxdB.jpg",
            "description" => "Sandwich with BBQ brisket.",
            "ingredients" => ["Bread", "BBQ Brisket", "Coleslaw", "Pickles", "Onions"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 10,
        ],
        [
            "name" => "Tuna Melt",
            "image" => "https://www.eatwell101.com/wp-content/uploads/2021/09/easy-tuna-melt-recipe.jpg",
            "description" => "Grilled sandwich with tuna and cheese.",
            "ingredients" => ["Bread", "Tuna Salad", "Cheese", "Butter", "Tomato"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 14,
        ],
        [
            "name" => "Avocado Toast",
            "image" => "https://i1.wp.com/myvegetarianroots.com/wp-content/uploads/2020/02/DSC_0027.jpeg?fit=1277%2C1920&ssl=1",
            "description" => "Toast with avocado spread.",
            "ingredients" => ["Bread", "Avocado", "Lemon", "Salt", "Pepper"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 11,
        ],
        [
            "name" => "Chicken Salad Wrap",
            "image" => "https://www.girlgonegourmet.com/wp-content/uploads/2016/05/Sun-Dried-Tomato-Chicken-Salad-Wraps-1.jpg",
            "description" => "Wrap with chicken salad.",
            "ingredients" => ["Tortilla", "Chicken Salad", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 7,
        ],
        [
            "name" => "Beef Burrito",
            "image" => "https://thekitchencommunity.org/wp-content/uploads/2021/02/Beef-Burrito-Recipe.jpg",
            "description" => "Burrito with beef and beans.",
            "ingredients" => ["Tortilla", "Beef", "Beans", "Rice", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],



        [
            "name" => "Chicken Quesadilla",
            "image" => "https://bigoven-res.cloudinary.com/image/upload/t_recipe-1280/chicken-quesadilla-0c7614.jpg",
            "description" => "Quesadilla with chicken and cheese.",
            "ingredients" => ["Tortilla", "Chicken", "Cheese", "Onion", "Peppers"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Veggie Wrap",
            "image" => "https://myfavoritelife.net/wp-content/uploads/2021/07/Thai-Peanut-Wraps.jpg",
            "description" => "Wrap with mixed vegetables.",
            "ingredients" => ["Tortilla", "Bell Peppers", "Cucumber", "Lettuce", "Hummus"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Pulled Pork Wrap",
            "image" => "https://i.pinimg.com/originals/92/6b/14/926b14bee63f6ed2aa7e35295fd4f6c0.png",
            "description" => "Wrap with pulled pork.",
            "ingredients" => ["Tortilla", "Pulled Pork", "BBQ Sauce", "Coleslaw", "Pickles"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 8,
        ],
        [
            "name" => "Shrimp Tacos",
            "image" => "https://valentinascorner.com/wp-content/uploads/2020/02/Shrimp-Taco-Recipe-1.jpg",
            "description" => "Tacos with shrimp and toppings.",
            "ingredients" => ["Tortilla", "Shrimp", "Cabbage", "Lime", "Sour Cream"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Burrito",
            "image" => "https://i.pinimg.com/originals/bb/85/60/bb85609e89baecaa1a7878acc4e70da2.jpg",
            "description" => "Burrito with chicken and beans.",
            "ingredients" => ["Tortilla", "Chicken", "Beans", "Rice", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Fish Burrito",
            "image" => "https://mlx1wfobjbs4.i.optimole.com/w:1024/h:683/q:mauto/rt:fill/g:sm/f:avif/https://www.recipedev.com/wp-content/uploads/2022/04/fish-burrito-recipe.jpeg",
            "description" => "Burrito with fish and rice.",
            "ingredients" => ["Tortilla", "Fish", "Rice", "Cabbage", "Salsa"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Steak Fajitas",
            "image" => "https://images.getbento.com/accounts/8f668701aa4b841bf51f6bd22df62eb9/media/images/57030Steak-Fajitas-Recipe-foodiecrush.com-17.jpg?w=768&fit=max&auto=compress,format",
            "description" => "Fajitas with steak and peppers.",
            "ingredients" => ["Steak", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Fajitas",
            "image" => "https://cdn.momsdish.com/wp-content/uploads/2021/04/Chicken-Fajitas-011-scaled.jpg",
            "description" => "Fajitas with chicken and peppers.",
            "ingredients" => ["Chicken", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Veggie Fajitas",
            "image" => "https://cookingmadehealthy.com/wp-content/uploads/2018/02/Fajita-Vegetables-2-768x1079.jpg",
            "description" => "Fajitas with mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Onion", "Mushrooms", "Tortilla", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Beef Enchiladas",
            "image" => "https://www.tasteofhome.com/wp-content/uploads/2017/10/Cheddar-Beef-Enchiladas_exps21076_GB2919407B01_10_3bC_RMS-2.jpg",
            "description" => "Enchiladas with beef and cheese.",
            "ingredients" => ["Tortilla", "Beef", "Cheese", "Onion", "Tomato Sauce"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Enchiladas",
            "image" => "https://www.tasteofhome.com/wp-content/uploads/2018/01/Creamy-Chicken-Enchiladas_EXPS_DIA18_33124_B05_25_2b-4.jpg",
            "description" => "Enchiladas with chicken and cheese.",
            "ingredients" => ["Tortilla", "Chicken", "Cheese", "Onion", "Tomato Sauce"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Enchiladas",
            "image" => "https://charlotteshares.blog/wp-content/uploads/2021/04/img_7050_jpg-864344006-1619625432545-e1619710420555.jpg",
            "description" => "Enchiladas with shrimp and cheese.",
            "ingredients" => ["Tortilla", "Shrimp", "Cheese", "Onion", "Tomato Sauce"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Vegetable Enchiladas",
            "image" => "https://www.spendwithpennies.com/wp-content/uploads/2021/03/FT-Veggie-Enchiladas-SpendWithPennies-9.jpg",
            "description" => "Enchiladas with mixed vegetables.",
            "ingredients" => ["Tortilla", "Bell Peppers", "Onion", "Cheese", "Tomato Sauce"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Beef Tostadas",
            "image" => "https://www.tasteandtellblog.com/wp-content/uploads/2020/04/Beef-Tostadas-1.jpg",
            "description" => "Tostadas with beef and toppings.",
            "ingredients" => ["Tostada", "Beef", "Lettuce", "Cheese", "Salsa"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Tostadas",
            "image" => "https://www.cookingclassy.com/wp-content/uploads/2013/02/slow-cooker-chicken-tostadas5.jpg",
            "description" => "Tostadas with chicken and toppings.",
            "ingredients" => ["Tostada", "Chicken", "Lettuce", "Cheese", "Salsa"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Tostadas",
            "image" => "https://www.the-girl-who-ate-everything.com/wp-content/uploads/2017/08/TheGirlWhoAteEverything_ShrimpTostadas_Hero2_Vertical.jpg",
            "description" => "Tostadas with shrimp and toppings.",
            "ingredients" => ["Tostada", "Shrimp", "Lettuce", "Cheese", "Salsa"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Vegetable Tostadas",
            "image" => "https://www.delishknowledge.com/wp-content/uploads/Vegetable-Tostadas_10-1024x1536.jpg",
            "description" => "Tostadas with mixed vegetables.",
            "ingredients" => ["Tostada", "Bell Peppers", "Onion", "Lettuce", "Cheese"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Beef Nachos",
            "image" => "https://iambaker.net/wp-content/uploads/2019/01/861A3209.nachos.jpg",
            "description" => "Nachos with beef and cheese.",
            "ingredients" => ["Tortilla Chips", "Beef", "Cheese", "Jalapenos", "Sour Cream"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Nachos",
            "image" => "https://www.archanaskitchen.com/images/archanaskitchen/0-Archanas-Kitchen-Recipes/2018/Spicy_Chicken_Nachos_Recipe_With_Salsa_And_Sour_Cream-1.jpg",
            "description" => "Nachos with chicken and cheese.",
            "ingredients" => ["Tortilla Chips", "Chicken", "Cheese", "Jalapenos", "Sour Cream"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Nachos",
            "image" => "https://stlcooks.com/wp-content/uploads/2014/06/12174.jpg",
            "description" => "Nachos with shrimp and cheese.",
            "ingredients" => ["Tortilla Chips", "Shrimp", "Cheese", "Jalapenos", "Sour Cream"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Vegetable Nachos",
            "image" => "https://thebusybaker.ca/wp-content/uploads/2017/12/rainbow-vegetable-skillet-nachos-fbig1-1024x1024.jpg",
            "description" => "Nachos with mixed vegetables.",
            "ingredients" => ["Tortilla Chips", "Bell Peppers", "Onion", "Cheese", "Sour Cream"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 15,
        ],
        [
            "name" => "Beef Quesadilla",
            "image" => "https://www.vindulge.com/wp-content/uploads/2023/02/Shredded-Beef-Quasadillas-FI.jpg",
            "description" => "Quesadilla with beef and cheese.",
            "ingredients" => ["Tortilla", "Beef", "Cheese", "Onion", "Peppers"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Fajitas",
            "image" => "https://cdn.momsdish.com/wp-content/uploads/2021/04/Chicken-Fajitas-011-scaled.jpg",
            "description" => "Fajitas with chicken and vegetables.",
            "ingredients" => ["Chicken", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 6,
        ],
        [
            "name" => "Beef Fajitas",
            "image" => "https://thestayathomechef.com/wp-content/uploads/2013/05/Steak-Fajitas-1.jpg",
            "description" => "Fajitas with beef and vegetables.",
            "ingredients" => ["Beef", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Fajitas",
            "image" => "https://www.dinneratthezoo.com/wp-content/uploads/2018/05/shrimp-fajitas-3.jpg",
            "description" => "Fajitas with shrimp and vegetables.",
            "ingredients" => ["Shrimp", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 13.50,
            "visible" => true,
            "restaurant_id" => 13,
        ],
        [
            "name" => "Vegetable Fajitas",
            "image" => "https://www.thelastfoodblog.com/wp-content/uploads/2019/05/open-vegetable-fajitas-side-on-768x1099.jpg",
            "description" => "Fajitas with mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Onion", "Zucchini", "Tortilla", "Cheese"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 15,
        ],
    ]

];
