<?php

return [

    'users' => [
        [
            'name' => 'Giuseppe',
            'surname' => 'Rossi',
            'email' => 'giusepperossi@example.com',
            'password' =>  'password123',
        ],
        [
            'name' => 'Mario',
            'surname' => 'Bianchi',
            'email' => 'mariobianchi@example.com',
            'password' =>  'password456',
        ],
        [
            'name' => 'Luca',
            'surname' => 'Verdi',
            'email' => 'lucaverdi@example.com',
            'password' =>  'password789',
        ],
        [
            'name' => 'Marco',
            'surname' => 'Rossi',
            'email' => 'marcorossi@example.com',
            'password' =>  'password1011',
        ],

        [
            'name' => 'Giuseppe',
            'surname' => 'Cassone',
            'email' => 'cassone@example.com',
            'password' =>  'password123',
        ]

    ],

    'restaurants' => [
        [
            'name' => 'Ristorante da Luigi',
            'image' => 'https://livitaly-666b.kxcdn.com/wp-content/uploads/2019/10/shutterstock_1054754711.jpg',
            'phone' => '+39 3517785963',
            'address' => 'Via Roma 10, Roma',
            'vat' => 'IT12345678901',
            'user_id' => 1
        ],
        [
            'name' => 'Pizzeria Bella Napoli',
            'image' => 'https://www.mrnystyleandtravel.com/wp-content/uploads/2018/07/Den-Exterior.jpg',
            'address' => 'Corso Italia 22, Napoli',
            'phone' => '+39 3781598745',
            'vat' => 'IT98765432109',
            'user_id' => 2
        ],
        [
            'name' => 'Trattoria Alla Vecchia',
            'image' => 'https://thearchitectsdiary.com/wp-content/uploads/2018/06/Best-Restaurant-Interior-Design-In-India-3.jpg',
            'address' => 'Piazza Garibaldi 15, Firenze',
            'phone' => '+39 3795896521',
            'vat' => 'IT19283746501',
            'user_id' => 3
        ],
        [
            'name' => 'Osteria Al Dente',
            'image' => 'https://flawless.life/wp-content/uploads/2020/02/Le_migliori_pizzerie_di_Milano_PiccolaIschia.jpg',
            'address' => 'Via Milano 5, Milano',
            'phone' => '+39 3253698547',
            'vat' => 'IT56473829100',
            'user_id' => 4
        ],
        [
            'name' => 'Ristorante Il Girasole',
            'image' => 'https://mangiaebevi.us/wp-content/uploads/2020/01/DSC4594-1024x683.jpg',
            'address' => 'Via Torino 18, Torino',
            'phone' => '+39 3782654851',
            'vat' => 'IT67584930210',
            'user_id' => 5
        ],
    ],

    'types' => [
        [
            'type' => 'Mexican',
        ],
        [
            'type' => 'Italian',
        ],
        [
            'type' => 'Pizzeria',
        ],
        [
            'type' => 'Chinese',
        ],
        // [
        //     'type' => 'Japanese',
        // ],
        [
            'type' => 'Thai',
        ],
        [
            'type' => 'Indian',
        ],
        [
            'type' => 'Fusion',
        ],
        [
            'type' => 'Greek',
        ],
        [
            'type' => 'Steakhouse'
        ]
    ],

    'dishes' => [
        [
            "name" => "Spaghetti Carbonara",
            "image" => "https://www.ricettaidea.it/articoli/ricette-regionali/lazio/original_spaghetti-alla-carbonara.jpg",
            "description" => "Spaghetti with egg cream and pancetta.",
            "ingredients" => ["Spaghetti", "Eggs", "Pancetta", "Pecorino", "Pepper"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Pizza Margherita",
            "image" => "https://vitaitaliantours.com.au/wp-content/uploads/2016/03/Neapolitan-Pizza-Margherita.jpg",
            "description" => "Classic pizza with tomato and mozzarella.",
            "ingredients" => ["Tomato", "Mozzarella", "Basil", "Olive Oil", "Salt"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Mushroom Risotto",
            "image" => "https://blog.giallozafferano.it/peperoncino88/wp-content/uploads/2017/10/DSC_0020.jpg",
            "description" => "Creamy risotto with porcini mushrooms.",
            "ingredients" => ["Rice", "Mushrooms", "Broth", "Butter", "Parmesan"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Lasagna",
            "image" => "https://facts.net/wp-content/uploads/2023/05/Slice-of-lasagna.jpeg",
            "description" => "Layers of pasta with meat sauce and béchamel.",
            "ingredients" => ["Pasta", "Meat Sauce", "Béchamel", "Parmesan", "Mozzarella"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Caprese Salad",
            "image" => "https://www.tasteoftravel.at/wp-content/uploads/Rezept-Caprese-Salat.jpg",
            "description" => "Tomato and mozzarella with fresh basil.",
            "ingredients" => ["Tomato", "Mozzarella", "Basil", "Olive Oil", "Salt"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chicken Cacciatore",
            "image" => "https://4.bp.blogspot.com/-sLQkRHQnI0g/V5y0Lj1C6QI/AAAAAAAAIL0/B1fHSzXrZaMAgZTOwgzFpNU0gAhVVT_RQCLcB/s640/pollo_padella.jpg",
            "description" => "Braised chicken with tomato and olives.",
            "ingredients" => ["Chicken", "Tomato", "Olives", "Wine", "Rosemary"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Fettuccine Alfredo",
            "image" => "https://www.thechunkychef.com/wp-content/uploads/2016/02/Roasted-Garlic-Cream-Sauce-6-1.jpg",
            "description" => "Pasta with creamy butter and parmesan sauce.",
            "ingredients" => ["Fettuccine", "Butter", "Parmesan", "Cream", "Pepper"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Tomato Bruschetta",
            "image" => "https://www.cucchiaio.it/content/cucchiaio/it/ricette/2009/11/ricetta-bruschetta-pomodoro/_jcr_content/header-par/image_single.img.jpg/1596625322419.jpg",
            "description" => "Toasted bread with fresh tomato and basil.",
            "ingredients" => ["Bread", "Tomato", "Basil", "Garlic", "Olive Oil"],
            "price" => 5.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Tiramisu",
            "image" => "https://www.divella.it/wp-content/uploads/2022/12/tiramisu.jpg",
            "description" => "Coffee-flavored dessert with mascarpone and ladyfingers.",
            "ingredients" => ["Mascarpone", "Ladyfingers", "Coffee", "Cocoa", "Sugar"],
            "price" => 6.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Gnocchi with Pesto",
            "image" => "https://lognocco.it/wp-content/uploads/2018/07/9-preparazione-ricetta-gnocchi-pesto.jpg",
            "description" => "Potato gnocchi with fresh pesto.",
            "ingredients" => ["Gnocchi", "Basil", "Garlic", "Pine Nuts", "Parmesan"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Beef Tagliata",
            "image" => "https://staticcookist.akamaized.net/wp-content/uploads/sites/21/2023/01/Tagliata-di-manzo.jpg",
            "description" => "Grilled beef with arugula and parmesan.",
            "ingredients" => ["Beef", "Arugula", "Parmesan", "Olive Oil", "Salt"],
            "price" => 18.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Penne Arrabbiata",
            "image" => "https://cdn.ilclubdellericette.it/wp-content/uploads/2021/09/penne-arrabbiata-1280x720.jpg",
            "description" => "Spicy pasta with tomato and chili pepper.",
            "ingredients" => ["Penne", "Tomato", "Chili Pepper", "Garlic", "Olive Oil"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Rice Balls",
            "image" => "image",
            "description" => "Fried rice balls filled with meat sauce.",
            "ingredients" => ["Rice", "Meat Sauce", "Peas", "Cheese", "Breadcrumbs"],
            "price" => 7.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Fried Calamari",
            "image" => "image",
            "description" => "Fried calamari served with lemon.",
            "ingredients" => ["Calamari", "Flour", "Oil", "Lemon", "Salt"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Pasta and Beans",
            "image" => "image",
            "description" => "Pasta soup with beans and pancetta.",
            "ingredients" => ["Pasta", "Beans", "Pancetta", "Tomato", "Rosemary"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Seafood Linguine",
            "image" => "image",
            "description" => "Linguine with mixed seafood.",
            "ingredients" => ["Linguine", "Shrimp", "Clams", "Tomato", "Garlic"],
            "price" => 16.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Vegetarian Pizza",
            "image" => "image",
            "description" => "Pizza with mixed vegetables.",
            "ingredients" => ["Dough", "Tomato", "Mozzarella", "Bell Peppers", "Olives"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Chicken Parmesan",
            "image" => "image",
            "description" => "Breaded chicken with parmesan.",
            "ingredients" => ["Chicken", "Breadcrumbs", "Parmesan", "Tomato Sauce", "Mozzarella"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Grilled Salmon",
            "image" => "image",
            "description" => "Salmon grilled with herbs.",
            "ingredients" => ["Salmon", "Olive Oil", "Lemon", "Garlic", "Dill"],
            "price" => 18.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chocolate Cake",
            "image" => "image",
            "description" => "Rich chocolate layered cake.",
            "ingredients" => ["Chocolate", "Flour", "Sugar", "Eggs", "Butter"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Minestrone Soup",
            "image" => "image",
            "description" => "Hearty vegetable soup.",
            "ingredients" => ["Tomato", "Carrot", "Celery", "Beans", "Pasta"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Eggplant Parmesan",
            "image" => "image",
            "description" => "Breaded eggplant with cheese.",
            "ingredients" => ["Eggplant", "Breadcrumbs", "Parmesan", "Tomato Sauce", "Mozzarella"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Garlic Bread",
            "image" => "image",
            "description" => "Toasted bread with garlic butter.",
            "ingredients" => ["Bread", "Butter", "Garlic", "Parsley", "Salt"],
            "price" => 4.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Lamb Chops",
            "image" => "image",
            "description" => "Grilled lamb with rosemary.",
            "ingredients" => ["Lamb", "Rosemary", "Garlic", "Olive Oil", "Salt"],
            "price" => 20.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Cheeseburger",
            "image" => "image",
            "description" => "Burger with cheese and toppings.",
            "ingredients" => ["Beef", "Cheese", "Lettuce", "Tomato", "Bun"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Pasta Primavera",
            "image" => "image",
            "description" => "Pasta with fresh vegetables.",
            "ingredients" => ["Pasta", "Bell Peppers", "Zucchini", "Tomato", "Garlic"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Shrimp Scampi",
            "image" => "image",
            "description" => "Shrimp in garlic butter sauce.",
            "ingredients" => ["Shrimp", "Garlic", "Butter", "Lemon", "Parsley"],
            "price" => 17.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Caesar Salad",
            "image" => "image",
            "description" => "Salad with Caesar dressing.",
            "ingredients" => ["Lettuce", "Croutons", "Parmesan", "Caesar Dressing", "Chicken"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Clam Chowder",
            "image" => "image",
            "description" => "Creamy soup with clams.",
            "ingredients" => ["Clams", "Potato", "Cream", "Onion", "Bacon"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "BBQ Ribs",
            "image" => "image",
            "description" => "Ribs with BBQ sauce.",
            "ingredients" => ["Ribs", "BBQ Sauce", "Garlic", "Brown Sugar", "Paprika"],
            "price" => 18.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Veggie Burger",
            "image" => "image",
            "description" => "Vegetarian burger with toppings.",
            "ingredients" => ["Veggie Patty", "Lettuce", "Tomato", "Cheese", "Bun"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Stuffed Peppers",
            "image" => "image",
            "description" => "Peppers stuffed with rice and meat.",
            "ingredients" => ["Bell Peppers", "Rice", "Ground Beef", "Tomato Sauce", "Cheese"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Fish Tacos",
            "image" => "image",
            "description" => "Tacos with fried fish.",
            "ingredients" => ["Fish", "Tortilla", "Cabbage", "Lime", "Sour Cream"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "French Onion Soup",
            "image" => "image",
            "description" => "Soup with caramelized onions.",
            "ingredients" => ["Onions", "Beef Broth", "Bread", "Cheese", "Thyme"],
            "price" => 7.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Pulled Pork Sandwich",
            "image" => "image",
            "description" => "Sandwich with pulled pork.",
            "ingredients" => ["Pulled Pork", "BBQ Sauce", "Bun", "Pickles", "Onion"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Margherita Pizza",
            "image" => "image",
            "description" => "Classic pizza with tomato and mozzarella.",
            "ingredients" => ["Tomato", "Mozzarella", "Basil", "Olive Oil", "Salt"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Grilled Chicken",
            "image" => "image",
            "description" => "Chicken grilled with herbs.",
            "ingredients" => ["Chicken", "Olive Oil", "Lemon", "Garlic", "Rosemary"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Spaghetti Bolognese",
            "image" => "image",
            "description" => "Spaghetti with meat sauce.",
            "ingredients" => ["Spaghetti", "Ground Beef", "Tomato", "Onion", "Garlic"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chicken Alfredo",
            "image" => "image",
            "description" => "Pasta with creamy Alfredo sauce.",
            "ingredients" => ["Pasta", "Chicken", "Cream", "Parmesan", "Garlic"],
            "price" => 13.50,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Beef Stroganoff",
            "image" => "image",
            "description" => "Beef with creamy mushroom sauce.",
            "ingredients" => ["Beef", "Mushrooms", "Sour Cream", "Onion", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Vegetable Stir Fry",
            "image" => "image",
            "description" => "Stir-fried mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Broccoli", "Carrots", "Soy Sauce", "Garlic"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Roast Beef",
            "image" => "image",
            "description" => "Slow-cooked roast beef.",
            "ingredients" => ["Beef", "Garlic", "Rosemary", "Olive Oil", "Salt"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Alfredo",
            "image" => "image",
            "description" => "Pasta with shrimp in Alfredo sauce.",
            "ingredients" => ["Pasta", "Shrimp", "Cream", "Parmesan", "Garlic"],
            "price" => 16.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Caesar Salad",
            "image" => "image",
            "description" => "Salad with chicken and Caesar dressing.",
            "ingredients" => ["Lettuce", "Chicken", "Croutons", "Parmesan", "Caesar Dressing"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Garlic Shrimp",
            "image" => "image",
            "description" => "Shrimp in garlic butter.",
            "ingredients" => ["Shrimp", "Garlic", "Butter", "Lemon", "Parsley"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Beef Tacos",
            "image" => "image",
            "description" => "Tacos with beef and toppings.",
            "ingredients" => ["Beef", "Tortilla", "Lettuce", "Tomato", "Cheese"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Chicken Tacos",
            "image" => "image",
            "description" => "Tacos with chicken and toppings.",
            "ingredients" => ["Chicken", "Tortilla", "Lettuce", "Tomato", "Cheese"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Fish Tacos",
            "image" => "image",
            "description" => "Tacos with fish and toppings.",
            "ingredients" => ["Fish", "Tortilla", "Cabbage", "Lime", "Sour Cream"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Vegetarian Tacos",
            "image" => "image",
            "description" => "Tacos with mixed vegetables.",
            "ingredients" => ["Tortilla", "Bell Peppers", "Onion", "Corn", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "BBQ Chicken Pizza",
            "image" => "image",
            "description" => "Pizza with BBQ chicken.",
            "ingredients" => ["Dough", "BBQ Sauce", "Chicken", "Onion", "Mozzarella"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Pepperoni Pizza",
            "image" => "image",
            "description" => "Pizza with pepperoni.",
            "ingredients" => ["Dough", "Tomato Sauce", "Pepperoni", "Mozzarella", "Olive Oil"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Four Cheese Pizza",
            "image" => "image",
            "description" => "Pizza with four types of cheese.",
            "ingredients" => ["Dough", "Tomato Sauce", "Mozzarella", "Parmesan", "Gorgonzola", "Ricotta"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Hawaiian Pizza",
            "image" => "image",
            "description" => "Pizza with ham and pineapple.",
            "ingredients" => ["Dough", "Tomato Sauce", "Ham", "Pineapple", "Mozzarella"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Buffalo Wings",
            "image" => "image",
            "description" => "Spicy chicken wings.",
            "ingredients" => ["Chicken Wings", "Buffalo Sauce", "Butter", "Garlic", "Celery"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Mozzarella Sticks",
            "image" => "image",
            "description" => "Fried mozzarella sticks.",
            "ingredients" => ["Mozzarella", "Breadcrumbs", "Eggs", "Flour", "Marinara Sauce"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Chicken Nuggets",
            "image" => "image",
            "description" => "Breaded and fried chicken pieces.",
            "ingredients" => ["Chicken", "Breadcrumbs", "Eggs", "Flour", "Ketchup"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Pork Chops",
            "image" => "image",
            "description" => "Grilled pork chops with herbs.",
            "ingredients" => ["Pork Chops", "Olive Oil", "Garlic", "Rosemary", "Salt"],
            "price" => 15.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Lamb Curry",
            "image" => "image",
            "description" => "Spicy lamb curry with rice.",
            "ingredients" => ["Lamb", "Curry Powder", "Coconut Milk", "Onion", "Garlic"],
            "price" => 18.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chicken Curry",
            "image" => "image",
            "description" => "Spicy chicken curry with rice.",
            "ingredients" => ["Chicken", "Curry Powder", "Coconut Milk", "Onion", "Garlic"],
            "price" => 16.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Beef Curry",
            "image" => "image",
            "description" => "Spicy beef curry with rice.",
            "ingredients" => ["Beef", "Curry Powder", "Coconut Milk", "Onion", "Garlic"],
            "price" => 17.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Vegetable Curry",
            "image" => "image",
            "description" => "Spicy vegetable curry with rice.",
            "ingredients" => ["Bell Peppers", "Carrots", "Coconut Milk", "Onion", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Salmon Sashimi",
            "image" => "image",
            "description" => "Fresh salmon sashimi.",
            "ingredients" => ["Salmon", "Soy Sauce", "Wasabi", "Ginger", "Lemon"],
            "price" => 20.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Tuna Sashimi",
            "image" => "image",
            "description" => "Fresh tuna sashimi.",
            "ingredients" => ["Tuna", "Soy Sauce", "Wasabi", "Ginger", "Lemon"],
            "price" => 20.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Beef Stir Fry",
            "image" => "image",
            "description" => "Stir-fried beef with vegetables.",
            "ingredients" => ["Beef", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Chicken Stir Fry",
            "image" => "image",
            "description" => "Stir-fried chicken with vegetables.",
            "ingredients" => ["Chicken", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
            "price" => 13.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Pork Stir Fry",
            "image" => "image",
            "description" => "Stir-fried pork with vegetables.",
            "ingredients" => ["Pork", "Bell Peppers", "Broccoli", "Soy Sauce", "Garlic"],
            "price" => 14.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Vegetable Stir Fry",
            "image" => "image",
            "description" => "Stir-fried mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Broccoli", "Carrots", "Soy Sauce", "Garlic"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Fish and Chips",
            "image" => "image",
            "description" => "Fried fish with chips.",
            "ingredients" => ["Fish", "Potatoes", "Flour", "Oil", "Salt"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chicken and Chips",
            "image" => "image",
            "description" => "Fried chicken with chips.",
            "ingredients" => ["Chicken", "Potatoes", "Flour", "Oil", "Salt"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Prawn Cocktail",
            "image" => "image",
            "description" => "Prawns in a creamy sauce.",
            "ingredients" => ["Prawns", "Mayonnaise", "Ketchup", "Lemon", "Lettuce"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Stuffed Mushrooms",
            "image" => "image",
            "description" => "Mushrooms stuffed with cheese.",
            "ingredients" => ["Mushrooms", "Cheese", "Breadcrumbs", "Garlic", "Parsley"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Egg Salad",
            "image" => "image",
            "description" => "Salad with boiled eggs.",
            "ingredients" => ["Eggs", "Lettuce", "Tomato", "Mayonnaise", "Onion"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Tuna Salad",
            "image" => "image",
            "description" => "Salad with tuna.",
            "ingredients" => ["Tuna", "Lettuce", "Tomato", "Onion", "Olive Oil"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Salmon Salad",
            "image" => "image",
            "description" => "Salad with salmon.",
            "ingredients" => ["Salmon", "Lettuce", "Tomato", "Onion", "Olive Oil"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Chicken Salad",
            "image" => "image",
            "description" => "Salad with chicken.",
            "ingredients" => ["Chicken", "Lettuce", "Tomato", "Onion", "Olive Oil"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Grilled Cheese Sandwich",
            "image" => "image",
            "description" => "Sandwich with melted cheese.",
            "ingredients" => ["Bread", "Cheese", "Butter", "Garlic", "Parsley"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Ham and Cheese Sandwich",
            "image" => "image",
            "description" => "Sandwich with ham and cheese.",
            "ingredients" => ["Bread", "Ham", "Cheese", "Butter", "Garlic"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Turkey Sandwich",
            "image" => "image",
            "description" => "Sandwich with turkey.",
            "ingredients" => ["Bread", "Turkey", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "BLT Sandwich",
            "image" => "image",
            "description" => "Sandwich with bacon, lettuce, and tomato.",
            "ingredients" => ["Bread", "Bacon", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Veggie Sandwich",
            "image" => "image",
            "description" => "Sandwich with vegetables.",
            "ingredients" => ["Bread", "Lettuce", "Tomato", "Cucumber", "Avocado"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Pastrami Sandwich",
            "image" => "image",
            "description" => "Sandwich with pastrami.",
            "ingredients" => ["Bread", "Pastrami", "Mustard", "Pickles", "Cheese"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Reuben Sandwich",
            "image" => "image",
            "description" => "Sandwich with corned beef and sauerkraut.",
            "ingredients" => ["Bread", "Corned Beef", "Sauerkraut", "Swiss Cheese", "Thousand Island Dressing"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Pulled Pork Sandwich",
            "image" => "image",
            "description" => "Sandwich with pulled pork.",
            "ingredients" => ["Bread", "Pulled Pork", "BBQ Sauce", "Coleslaw", "Pickles"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Meatball Sandwich",
            "image" => "image",
            "description" => "Sandwich with meatballs.",
            "ingredients" => ["Bread", "Meatballs", "Marinara Sauce", "Provolone Cheese", "Parmesan"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Chicken Parmesan Sandwich",
            "image" => "image",
            "description" => "Sandwich with chicken parmesan.",
            "ingredients" => ["Bread", "Chicken Parmesan", "Marinara Sauce", "Mozzarella", "Parmesan"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Philly Cheesesteak",
            "image" => "image",
            "description" => "Sandwich with steak and cheese.",
            "ingredients" => ["Bread", "Steak", "Cheese", "Onions", "Peppers"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Cubano Sandwich",
            "image" => "image",
            "description" => "Sandwich with ham, pork, and pickles.",
            "ingredients" => ["Bread", "Ham", "Pork", "Pickles", "Mustard"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Egg Salad Sandwich",
            "image" => "image",
            "description" => "Sandwich with egg salad.",
            "ingredients" => ["Bread", "Egg Salad", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 8.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Shrimp Po' Boy",
            "image" => "image",
            "description" => "Sandwich with fried shrimp.",
            "ingredients" => ["Bread", "Fried Shrimp", "Lettuce", "Tomato", "Remoulade Sauce"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Turkey Club Sandwich",
            "image" => "image",
            "description" => "Triple-decker sandwich with turkey, bacon, and lettuce.",
            "ingredients" => ["Bread", "Turkey", "Bacon", "Lettuce", "Tomato"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Italian Sub",
            "image" => "image",
            "description" => "Sub with Italian meats and cheeses.",
            "ingredients" => ["Bread", "Salami", "Ham", "Provolone", "Olive Oil"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "BBQ Pulled Chicken Sandwich",
            "image" => "image",
            "description" => "Sandwich with BBQ pulled chicken.",
            "ingredients" => ["Bread", "Pulled Chicken", "BBQ Sauce", "Coleslaw", "Pickles"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "French Dip Sandwich",
            "image" => "image",
            "description" => "Sandwich with roast beef and au jus.",
            "ingredients" => ["Bread", "Roast Beef", "Swiss Cheese", "Au Jus", "Onions"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Buffalo Chicken Sandwich",
            "image" => "image",
            "description" => "Sandwich with buffalo chicken.",
            "ingredients" => ["Bread", "Buffalo Chicken", "Lettuce", "Tomato", "Blue Cheese Dressing"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "BBQ Brisket Sandwich",
            "image" => "image",
            "description" => "Sandwich with BBQ brisket.",
            "ingredients" => ["Bread", "BBQ Brisket", "Coleslaw", "Pickles", "Onions"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Tuna Melt",
            "image" => "image",
            "description" => "Grilled sandwich with tuna and cheese.",
            "ingredients" => ["Bread", "Tuna Salad", "Cheese", "Butter", "Tomato"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Avocado Toast",
            "image" => "image",
            "description" => "Toast with avocado spread.",
            "ingredients" => ["Bread", "Avocado", "Lemon", "Salt", "Pepper"],
            "price" => 7.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Chicken Salad Wrap",
            "image" => "image",
            "description" => "Wrap with chicken salad.",
            "ingredients" => ["Tortilla", "Chicken Salad", "Lettuce", "Tomato", "Mayonnaise"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Beef Burrito",
            "image" => "image",
            "description" => "Burrito with beef and beans.",
            "ingredients" => ["Tortilla", "Beef", "Beans", "Rice", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chicken Quesadilla",
            "image" => "image",
            "description" => "Quesadilla with chicken and cheese.",
            "ingredients" => ["Tortilla", "Chicken", "Cheese", "Onion", "Peppers"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Veggie Wrap",
            "image" => "image",
            "description" => "Wrap with mixed vegetables.",
            "ingredients" => ["Tortilla", "Bell Peppers", "Cucumber", "Lettuce", "Hummus"],
            "price" => 8.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Pulled Pork Wrap",
            "image" => "image",
            "description" => "Wrap with pulled pork.",
            "ingredients" => ["Tortilla", "Pulled Pork", "BBQ Sauce", "Coleslaw", "Pickles"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Tacos",
            "image" => "image",
            "description" => "Tacos with shrimp and toppings.",
            "ingredients" => ["Tortilla", "Shrimp", "Cabbage", "Lime", "Sour Cream"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Burrito",
            "image" => "image",
            "description" => "Burrito with chicken and beans.",
            "ingredients" => ["Tortilla", "Chicken", "Beans", "Rice", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Fish Burrito",
            "image" => "image",
            "description" => "Burrito with fish and rice.",
            "ingredients" => ["Tortilla", "Fish", "Rice", "Cabbage", "Salsa"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Steak Fajitas",
            "image" => "image",
            "description" => "Fajitas with steak and peppers.",
            "ingredients" => ["Steak", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Chicken Fajitas",
            "image" => "image",
            "description" => "Fajitas with chicken and peppers.",
            "ingredients" => ["Chicken", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Veggie Fajitas",
            "image" => "image",
            "description" => "Fajitas with mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Onion", "Mushrooms", "Tortilla", "Cheese"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Beef Enchiladas",
            "image" => "image",
            "description" => "Enchiladas with beef and cheese.",
            "ingredients" => ["Tortilla", "Beef", "Cheese", "Onion", "Tomato Sauce"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Chicken Enchiladas",
            "image" => "image",
            "description" => "Enchiladas with chicken and cheese.",
            "ingredients" => ["Tortilla", "Chicken", "Cheese", "Onion", "Tomato Sauce"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Shrimp Enchiladas",
            "image" => "image",
            "description" => "Enchiladas with shrimp and cheese.",
            "ingredients" => ["Tortilla", "Shrimp", "Cheese", "Onion", "Tomato Sauce"],
            "price" => 11.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Vegetable Enchiladas",
            "image" => "image",
            "description" => "Enchiladas with mixed vegetables.",
            "ingredients" => ["Tortilla", "Bell Peppers", "Onion", "Cheese", "Tomato Sauce"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Beef Tostadas",
            "image" => "image",
            "description" => "Tostadas with beef and toppings.",
            "ingredients" => ["Tostada", "Beef", "Lettuce", "Cheese", "Salsa"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Chicken Tostadas",
            "image" => "image",
            "description" => "Tostadas with chicken and toppings.",
            "ingredients" => ["Tostada", "Chicken", "Lettuce", "Cheese", "Salsa"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Shrimp Tostadas",
            "image" => "image",
            "description" => "Tostadas with shrimp and toppings.",
            "ingredients" => ["Tostada", "Shrimp", "Lettuce", "Cheese", "Salsa"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Vegetable Tostadas",
            "image" => "image",
            "description" => "Tostadas with mixed vegetables.",
            "ingredients" => ["Tostada", "Bell Peppers", "Onion", "Lettuce", "Cheese"],
            "price" => 9.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Beef Nachos",
            "image" => "image",
            "description" => "Nachos with beef and cheese.",
            "ingredients" => ["Tortilla Chips", "Beef", "Cheese", "Jalapenos", "Sour Cream"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 1,
        ],
        [
            "name" => "Chicken Nachos",
            "image" => "image",
            "description" => "Nachos with chicken and cheese.",
            "ingredients" => ["Tortilla Chips", "Chicken", "Cheese", "Jalapenos", "Sour Cream"],
            "price" => 10.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Shrimp Nachos",
            "image" => "image",
            "description" => "Nachos with shrimp and cheese.",
            "ingredients" => ["Tortilla Chips", "Shrimp", "Cheese", "Jalapenos", "Sour Cream"],
            "price" => 11.00,
            "visible" => true,
            "restaurant_id" => 2,
        ],
        [
            "name" => "Vegetable Nachos",
            "image" => "image",
            "description" => "Nachos with mixed vegetables.",
            "ingredients" => ["Tortilla Chips", "Bell Peppers", "Onion", "Cheese", "Sour Cream"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Beef Quesadilla",
            "image" => "image",
            "description" => "Quesadilla with beef and cheese.",
            "ingredients" => ["Tortilla", "Beef", "Cheese", "Onion", "Peppers"],
            "price" => 9.50,
            "visible" => true,
            "restaurant_id" => 3,
        ],
        [
            "name" => "Chicken Fajitas",
            "image" => "image",
            "description" => "Fajitas with chicken and vegetables.",
            "ingredients" => ["Chicken", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 12.00,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Beef Fajitas",
            "image" => "image",
            "description" => "Fajitas with beef and vegetables.",
            "ingredients" => ["Beef", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 12.50,
            "visible" => true,
            "restaurant_id" => 4,
        ],
        [
            "name" => "Shrimp Fajitas",
            "image" => "image",
            "description" => "Fajitas with shrimp and vegetables.",
            "ingredients" => ["Shrimp", "Bell Peppers", "Onion", "Tortilla", "Cheese"],
            "price" => 13.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
        [
            "name" => "Vegetable Fajitas",
            "image" => "image",
            "description" => "Fajitas with mixed vegetables.",
            "ingredients" => ["Bell Peppers", "Onion", "Zucchini", "Tortilla", "Cheese"],
            "price" => 10.50,
            "visible" => true,
            "restaurant_id" => 5,
        ],
    ],
];
